// This file is auto-generated by @hey-api/openapi-ts

export const AnswerFreeTextSchema = {
    type: 'object',
    title: 'AnswerFreeText',
    description: 'A free-text Answer supplied by a Candidate',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'answers',
            default: 'answers'
        },
        attributes: {
            type: 'object',
            additionalProperties: false,
            properties: {
                answer: {
                    type: 'string',
                    pattern: '^[\\w\\s\\d\\p{P}\\r\\n]+',
                    minLength: 1,
                    maxLength: 190
                }
            }
        },
        relationships: {
            type: 'object',
            additionalProperties: false,
            properties: {
                candidate_assessment: {
                    $ref: '#/components/schemas/relationshipCandidateAssessment'
                },
                question: {
                    $ref: '#/components/schemas/relationshipQuestion'
                }
            },
            required: [
                'candidate_assessment',
                'question'
            ]
        }
    },
    required: [
        'id',
        'type',
        'attributes',
        'relationships'
    ]
} as const;

export const resourceIdSchema = {
    type: 'string',
    title: 'resourceId',
    description: 'Resource ID.',
    format: 'uuid',
    pattern: '^[A-Za-z0-9_]+',
    maxLength: 36
} as const;

export const relationshipCandidateAssessmentSchema = {
    type: 'object',
    title: 'relationshipCandidateAssessment',
    description: 'CandidateAssessment relationship object',
    additionalProperties: false,
    properties: {
        data: {
            type: 'object',
            additionalProperties: false,
            properties: {
                type: {
                    const: 'candidate-assessments',
                    readOnly: true,
                    default: 'candidate-assessments'
                },
                id: {
                    $ref: '#/components/schemas/resourceId'
                }
            },
            required: [
                'type',
                'id'
            ]
        }
    },
    required: [
        'data'
    ]
} as const;

export const relationshipQuestionSchema = {
    type: 'object',
    title: 'relationshipQuestion',
    description: 'Question relationship object',
    additionalProperties: false,
    properties: {
        data: {
            type: 'object',
            additionalProperties: false,
            properties: {
                type: {
                    const: 'questions',
                    readOnly: true,
                    default: 'questions'
                },
                id: {
                    $ref: '#/components/schemas/resourceId'
                }
            },
            required: [
                'type',
                'id'
            ]
        }
    },
    required: [
        'data'
    ]
} as const;

export const AnswerRelationshipAnswerOptionSchema = {
    type: 'object',
    title: 'AnswerRelationshipAnswerOption',
    description: 'An AnswerOption selected by a Candidate',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'answers',
            default: 'answers'
        },
        relationships: {
            type: 'object',
            additionalProperties: false,
            properties: {
                candidate_assessment: {
                    $ref: '#/components/schemas/relationshipCandidateAssessment'
                },
                answer_option: {
                    $ref: '#/components/schemas/relationshipAnswerOption'
                },
                question: {
                    $ref: '#/components/schemas/relationshipQuestion'
                }
            },
            required: [
                'candidate_assessment',
                'answer_option',
                'question'
            ]
        }
    },
    required: [
        'id',
        'type',
        'relationships'
    ]
} as const;

export const relationshipAnswerOptionSchema = {
    type: 'object',
    title: 'relationshipAnswerOption',
    description: 'AnswerOption relationship object',
    additionalProperties: false,
    properties: {
        data: {
            type: 'object',
            additionalProperties: false,
            properties: {
                type: {
                    const: 'answer-options',
                    readOnly: true,
                    default: 'answer-options'
                },
                id: {
                    $ref: '#/components/schemas/resourceId'
                }
            },
            required: [
                'type',
                'id'
            ]
        }
    },
    required: [
        'data'
    ]
} as const;

export const CandidateSchema = {
    type: 'object',
    title: 'Candidate',
    description: 'Person who completes a CandidateAssessment.',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId',
            description: 'Unique identifier for the given candidate.'
        },
        type: {
            const: 'candidates',
            default: 'candidates'
        },
        attributes: {
            type: 'object',
            additionalProperties: false,
            properties: {
                first_name: {
                    type: 'string',
                    format: 'regex',
                    pattern: '^[A-Za-z -_]+',
                    maxLength: 190
                },
                surname: {
                    type: 'string',
                    format: 'regex',
                    pattern: '^[A-Za-z -_]+',
                    maxLength: 190
                },
                email: {
                    type: 'string',
                    format: 'email',
                    maxLength: 190
                },
                email_verified: {
                    type: 'boolean',
                    description: 'Set to true if the candidate\'s email has been verified.'
                },
                created_at: {
                    type: 'string',
                    description: 'Timestamp for record creation.',
                    format: 'date-time',
                    maxLength: 50,
                    readOnly: true
                },
                updated_at: {
                    type: [
                        'string',
                        'null'
                    ],
                    description: 'Timestamp for last update.',
                    format: 'date-time',
                    maxLength: 50,
                    readOnly: true
                },
                external_reference: {
                    type: [
                        'string',
                        'null'
                    ],
                    description: 'A reference you can use to link with a candidate in another system.',
                    format: 'regex',
                    pattern: '^[A-Za-z0-9 -_\\.]+',
                    maxLength: 190
                },
                gdpr_approval_date: {
                    type: 'string',
                    format: 'date-time',
                    maxLength: 50
                }
            },
            required: [
                'first_name',
                'surname',
                'email'
            ]
        }
    },
    required: [
        'id',
        'type',
        'attributes'
    ],
    examples: [
        {
            id: '142',
            first_name: 'Alice',
            surname: 'Smith',
            email: 'alice.smith@gmail.com',
            email_verified: true,
            created_at: '2018-01-01T12:00:00.000Z',
            updated_at: '2018-01-01T12:00:00.000Z',
            external_reference: 'Q705'
        }
    ]
} as const;

export const CandidateAssessmentActionSchema = {
    type: 'object',
    title: 'CandidateAssessmentAction',
    description: 'An Action resource for a CandidateAssessment.',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'candidate-assessment-actions',
            default: 'candidate-assessment-actions'
        },
        attributes: {
            type: 'object',
            additionalProperties: false,
            properties: {
                action: {
                    type: 'string',
                    enum: [
                        'start',
                        'finish'
                    ],
                    default: 'start'
                }
            },
            required: [
                'action'
            ]
        },
        relationships: {
            type: 'object',
            additionalProperties: false,
            properties: {
                'candidate-assessment': {
                    type: 'object',
                    additionalProperties: false,
                    properties: {
                        data: {
                            type: 'object',
                            additionalProperties: false,
                            properties: {
                                type: {
                                    const: 'candidate-assessments',
                                    default: 'candidate-assessments'
                                },
                                id: {
                                    $ref: '#/components/schemas/resourceId'
                                }
                            },
                            required: [
                                'type',
                                'id'
                            ]
                        }
                    },
                    required: [
                        'data'
                    ]
                }
            },
            required: [
                'candidate-assessment'
            ]
        }
    },
    required: [
        'type',
        'attributes',
        'relationships'
    ]
} as const;

export const ErrorSchema = {
    type: 'object',
    title: 'Error',
    description: 'Standard error object in a response.',
    additionalProperties: false,
    properties: {
        title: {
            type: 'string',
            format: 'regex',
            pattern: '^[A-Za-z0-9 -_]+',
            maxLength: 190,
            readOnly: true
        },
        detail: {
            type: 'string',
            pattern: '^[\\w\\s\\d\\p{P}\\r\\n]+',
            maxLength: 999,
            readOnly: true
        },
        code: {
            type: 'string',
            pattern: '^[A-Z_]+',
            maxLength: 25,
            readOnly: true
        },
        status: {
            type: 'integer',
            format: 'int32',
            minimum: 100,
            maximum: 505,
            readOnly: true,
            examples: [
                404
            ]
        }
    },
    required: [
        'title',
        'detail',
        'code',
        'status'
    ]
} as const;

export const metaCollectionPaginationSchema = {
    type: 'object',
    title: 'metaCollectionPagination',
    description: 'Standard pagination object in a meta response object.',
    additionalProperties: false,
    properties: {
        resource_count: {
            type: 'integer',
            format: 'int32',
            minimum: 1,
            maximum: 99,
            readOnly: true
        },
        page_count: {
            type: 'integer',
            format: 'int32',
            minimum: 1,
            maximum: 999,
            readOnly: true
        }
    },
    required: [
        'resource_count',
        'page_count'
    ],
    examples: [
        {
            resource_count: 'string',
            page_count: 'string'
        }
    ]
} as const;

export const linksCollectionPaginationSchema = {
    type: 'object',
    title: 'linksCollectionPagination',
    description: 'Object in a Response that provides pagination Links',
    additionalProperties: false,
    properties: {
        first: {
            type: 'string',
            description: 'To be explicit always include the field, but set to null if not applicable.',
            format: 'uri',
            maxLength: 190,
            readOnly: true
        },
        next: {
            type: 'string',
            description: 'To be explicit always include the field, but set to null if not applicable.',
            format: 'uri',
            maxLength: 190,
            readOnly: true
        },
        prev: {
            type: 'string',
            description: 'To be explicit always include the field, but set to null if not applicable.',
            format: 'uri',
            maxLength: 190,
            readOnly: true
        },
        last: {
            type: 'string',
            description: 'To be explicit always include the field, but set to null if not applicable.',
            format: 'uri',
            maxLength: 190,
            readOnly: true
        }
    },
    required: [
        'first'
    ]
} as const;

export const AssessmentSchema = {
    type: 'object',
    title: 'Assessment',
    description: 'Test template from which a CandidateAssessment is created.',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'assessments',
            default: 'assessments'
        },
        attributes: {
            type: 'object',
            additionalProperties: false,
            properties: {
                type: {
                    type: 'string',
                    format: 'regex',
                    pattern: '^[A-Za-z0-9-_]+',
                    maxLength: 25,
                    readOnly: true
                },
                title: {
                    type: 'string',
                    format: 'regex',
                    pattern: '^[A-Za-z0-9 -_]+',
                    maxLength: 190,
                    readOnly: true
                },
                language: {
                    $ref: '#/components/schemas/Language'
                },
                description: {
                    type: [
                        'string',
                        'null'
                    ],
                    format: 'regex',
                    pattern: '^[\\w\\s\\d\\p{P}\\r\\n]+',
                    maxLength: 190,
                    readOnly: true
                },
                'time-limit': {
                    type: [
                        'string',
                        'null'
                    ],
                    format: 'duration',
                    maxLength: 10,
                    readOnly: true,
                    examples: [
                        'PT30M'
                    ]
                },
                introduction: {
                    type: [
                        'string',
                        'null'
                    ],
                    pattern: '^[\\w\\s\\d\\p{P}\\r\\n]+',
                    maxLength: 2500,
                    readOnly: true
                },
                conclusion: {
                    type: [
                        'string',
                        'null'
                    ],
                    pattern: '^[\\w\\s\\d\\p{P}\\r\\n]+',
                    maxLength: 2500
                }
            },
            required: [
                'type',
                'title'
            ]
        }
    },
    required: [
        'id',
        'type',
        'attributes'
    ]
} as const;

export const LanguageSchema = {
    type: 'string',
    enum: [
        'en',
        'es',
        'fr',
        'de'
    ],
    title: 'Language',
    description: 'ISO 639-1. Possibly 639:2023 when available.',
    default: 'en',
    examples: [
        'en'
    ]
} as const;

export const CandidateAssessmentSchema = {
    type: 'object',
    title: 'CandidateAssessment',
    description: 'An Assessment assigned to a Candidate.',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'candidate-assessments',
            default: 'candidate-assessments'
        },
        attributes: {
            type: 'object',
            additionalProperties: false,
            properties: {
                url: {
                    type: 'string',
                    format: 'uri',
                    maxLength: 190,
                    readOnly: true
                },
                created_at: {
                    type: 'string',
                    format: 'date-time',
                    maxLength: 50,
                    readOnly: true
                },
                updated_at: {
                    type: [
                        'string',
                        'null'
                    ],
                    format: 'date-time',
                    maxLength: 50,
                    readOnly: true
                },
                started_at: {
                    type: [
                        'string',
                        'null'
                    ],
                    format: 'date-time',
                    maxLength: 50,
                    readOnly: true
                },
                completed_at: {
                    type: [
                        'string',
                        'null'
                    ],
                    format: 'date-time',
                    maxLength: 50,
                    readOnly: true
                }
            },
            required: [
                'url'
            ]
        },
        relationships: {
            type: 'object',
            additionalProperties: false,
            properties: {
                candidate: {
                    $ref: '#/components/schemas/relationshipCandidate'
                },
                assessment: {
                    $ref: '#/components/schemas/relationshipAssessment'
                }
            }
        },
        links: {
            type: 'object',
            additionalProperties: false,
            properties: {
                current_question: {
                    type: 'string',
                    format: 'uri',
                    maxLength: 190,
                    readOnly: true
                }
            }
        }
    },
    required: [
        'id',
        'type',
        'attributes'
    ]
} as const;

export const relationshipCandidateSchema = {
    type: 'object',
    title: 'relationshipCandidate',
    description: 'Candidate relationship object',
    additionalProperties: false,
    properties: {
        data: {
            type: 'object',
            additionalProperties: false,
            properties: {
                type: {
                    const: 'candidates',
                    readOnly: true,
                    default: 'candidates'
                },
                id: {
                    $ref: '#/components/schemas/resourceId'
                }
            },
            required: [
                'type',
                'id'
            ]
        }
    },
    required: [
        'data'
    ]
} as const;

export const relationshipAssessmentSchema = {
    type: 'object',
    title: 'relationshipAssessment',
    description: 'Assessment relationship object',
    additionalProperties: false,
    properties: {
        data: {
            type: 'object',
            additionalProperties: false,
            properties: {
                type: {
                    const: 'assessments',
                    readOnly: true,
                    default: 'assessments'
                },
                id: {
                    $ref: '#/components/schemas/resourceId'
                }
            },
            required: [
                'type',
                'id'
            ]
        }
    },
    required: [
        'data'
    ]
} as const;

export const ScoreSetSchema = {
    type: 'object',
    title: 'ScoreSet',
    description: 'A set of scores for a CandidateAssessment.',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'score-sets',
            readOnly: true,
            default: 'score-sets'
        },
        attributes: {
            type: 'object',
            additionalProperties: false,
            properties: {
                behavioural_scores: {
                    type: 'array',
                    maxItems: 999,
                    readOnly: true,
                    items: {
                        type: 'object',
                        additionalProperties: false,
                        properties: {
                            name: {
                                type: 'string',
                                format: 'regex',
                                pattern: '^[A-Za-z0-9 -_]+',
                                maxLength: 190,
                                readOnly: true
                            },
                            score: {
                                type: 'integer',
                                format: 'int32',
                                minimum: 0,
                                maximum: 6,
                                readOnly: true
                            }
                        },
                        required: [
                            'name',
                            'score'
                        ]
                    }
                },
                overall_score: {
                    type: 'number',
                    readOnly: true
                }
            },
            required: [
                'overall_score'
            ]
        },
        relationships: {
            type: 'object',
            additionalProperties: false,
            properties: {
                candidate_assessments: {
                    $ref: '#/components/schemas/relationshipCandidateAssessment'
                }
            }
        }
    },
    required: [
        'id',
        'type',
        'attributes'
    ]
} as const;

export const ReportSchema = {
    type: 'object',
    title: 'Report',
    description: 'Easy-to-read results of an Assessment.',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'reports',
            default: 'reports'
        },
        attributes: {
            type: 'object',
            additionalProperties: false,
            properties: {
                title: {
                    type: 'string',
                    format: 'regex',
                    pattern: '^[A-Za-z0-9 -_]+',
                    maxLength: 190,
                    readOnly: true
                },
                description: {
                    type: 'string',
                    format: 'regex',
                    pattern: '^[\\w\\s\\d\\p{P}\\r\\n]+',
                    maxLength: 190,
                    readOnly: true
                },
                created_at: {
                    type: 'string',
                    format: 'date-time',
                    maxLength: 50,
                    readOnly: true
                },
                updated_at: {
                    type: [
                        'string',
                        'null'
                    ],
                    format: 'date-time',
                    maxLength: 50,
                    readOnly: true
                }
            },
            required: [
                'title'
            ]
        }
    },
    required: [
        'id',
        'type',
        'attributes'
    ]
} as const;

export const QuestionSchema = {
    type: 'object',
    title: 'Question',
    description: 'An item on an Assessment that offers one or more AnswerOptions',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'questions',
            default: 'questions'
        },
        attributes: {
            oneOf: [
                {
                    $ref: '#/components/schemas/QuestionAttributesBasic'
                },
                {
                    $ref: '#/components/schemas/QuestionAttributesNumberPath'
                },
                {
                    $ref: '#/components/schemas/QuestionAttributesColourPath'
                }
            ]
        },
        relationships: {
            type: 'object',
            additionalProperties: false
        }
    },
    required: [
        'id',
        'type',
        'attributes'
    ]
} as const;

export const QuestionAttributesBasicSchema = {
    title: 'QuestionAttributesBasic',
    description: 'A set of attributes used in basic questions',
    allOf: [
        {
            $ref: '#/components/schemas/QuestionAttributesCore'
        },
        {
            type: 'object',
            additionalProperties: false,
            properties: {
                text: {
                    type: 'string',
                    format: 'regex',
                    pattern: '^[\\w\\s\\d\\p{P}\\r\\n]+',
                    maxLength: 190,
                    readOnly: true
                },
                image_url: {
                    type: 'string',
                    format: 'uri',
                    maxLength: 190,
                    readOnly: true
                },
                additional_answer_options: {
                    type: 'array',
                    maxItems: 2,
                    readOnly: true,
                    uniqueItems: true,
                    items: {
                        type: 'string',
                        enum: [
                            'SKIP',
                            'NOT_APPLICABLE'
                        ],
                        readOnly: true
                    }
                }
            }
        }
    ]
} as const;

export const QuestionAttributesCoreSchema = {
    type: 'object',
    title: 'QuestionAttributesCore',
    description: 'A set of attributes shared by all Questions',
    additionalProperties: false,
    properties: {
        question_type: {
            type: 'string',
            enum: [
                'SJT_MOST2',
                'SJT_MOST3',
                'SJT_MOST_LEAST',
                'SORTING',
                'VERBAL_HORIZONTAL',
                'VERBAL_VERTICAL',
                'NUMERICAL_HORIZONTAL',
                'NUMERICAL_VERTICAL',
                'NUMBER_PATH'
            ],
            readOnly: true
        },
        language: {
            $ref: '#/components/schemas/Language'
        },
        answer_order: {
            type: 'string',
            enum: [
                'RANDOM',
                'STATIC'
            ],
            description: 'Possibly future options of ALPHA_ASC, etc.',
            readOnly: true,
            default: 'STATIC'
        },
        answer_required: {
            type: 'boolean',
            readOnly: true,
            default: false
        }
    },
    required: [
        'question_type'
    ]
} as const;

export const QuestionAttributesNumberPathSchema = {
    title: 'QuestionAttributesNumberPath',
    description: 'A set of attributes for the NumberPath-style Question',
    examples: [
        {
            id: '497f6eca-6276-4993-bfeb-53cbbbba6f08',
            type: 'questions',
            attributes: {
                type: 'NUMBER_PATH',
                text: 'Match the target number to the start number to win.',
                language: 'en',
                answer_order: 'RANDOM'
            },
            relationships: {},
            start_num: 1,
            target_num: 10,
            steps: [
                {
                    step_num: 1,
                    step_options: [
                        {
                            option_label: '+ 1',
                            option_operator: 'ADD',
                            option_value: 1
                        },
                        {
                            option_label: '+ 2',
                            option_operator: 'ADD',
                            option_value: 2
                        },
                        {
                            option_label: '+ 3',
                            option_operator: 'ADD',
                            option_value: 3
                        },
                        {
                            option_label: '+ 4',
                            option_operator: 'ADD',
                            option_value: 4
                        }
                    ]
                },
                {
                    step_num: 2,
                    step_options: [
                        {
                            option_label: 'x 2',
                            option_operator: 'MULTIPLY',
                            option_value: 2
                        },
                        {
                            option_label: '- 1',
                            option_operator: 'SUBTRACT',
                            option_value: 1
                        },
                        {
                            option_label: '/ 2',
                            option_operator: 'DIVIDE',
                            option_value: 2
                        },
                        {
                            option_label: '+ 3',
                            option_operator: 'ADD',
                            option_value: 3
                        }
                    ]
                },
                {
                    step_num: 3,
                    step_options: [
                        {
                            optionLabel: '- 1',
                            option_operator: 'SUBTRACT',
                            option_value: 1
                        },
                        {
                            optionLabel: '- 2',
                            option_operator: 'SUBTRACT',
                            option_value: 2
                        },
                        {
                            optionLabel: '- 3',
                            option_operator: 'SUBTRACT',
                            option_value: 3
                        },
                        {
                            optionLabel: '- 4',
                            option_operator: 'SUBTRACT',
                            option_value: 4
                        }
                    ]
                }
            ]
        }
    ],
    allOf: [
        {
            $ref: '#/components/schemas/QuestionAttributesCore'
        },
        {
            type: 'object',
            additionalProperties: false,
            properties: {
                start_num: {
                    type: 'integer',
                    format: 'int32',
                    minimum: -2147483648,
                    maximum: 2147483647,
                    readOnly: true
                },
                target_num: {
                    type: 'integer',
                    format: 'int32',
                    minimum: -2147483648,
                    maximum: 2147483647,
                    readOnly: true
                },
                steps: {
                    type: 'array',
                    minItems: 1,
                    maxItems: 25,
                    items: {
                        type: 'object',
                        additionalProperties: false,
                        properties: {
                            step_num: {
                                type: 'integer',
                                format: 'int32',
                                minimum: -2147483648,
                                maximum: 2147483647,
                                readOnly: true
                            },
                            step_options: {
                                type: 'array',
                                minItems: 1,
                                maxItems: 10,
                                items: {
                                    type: 'object',
                                    additionalProperties: false,
                                    properties: {
                                        option_label: {
                                            type: 'string',
                                            pattern: '^[\\w\\s\\d\\p{P}]+',
                                            maxLength: 50,
                                            readOnly: true,
                                            examples: [
                                                'x 2'
                                            ]
                                        },
                                        option_operator: {
                                            type: 'string',
                                            enum: [
                                                'ADD',
                                                'SUBTRACT',
                                                'MULTIPLY',
                                                'DIVIDE',
                                                'POWER',
                                                'ROOT'
                                            ],
                                            readOnly: true
                                        },
                                        option_operand: {
                                            type: 'number',
                                            format: 'float',
                                            readOnly: true
                                        }
                                    },
                                    required: [
                                        'option_operator',
                                        'option_operand'
                                    ]
                                }
                            }
                        },
                        required: [
                            'step_num',
                            'step_options'
                        ]
                    }
                }
            },
            required: [
                'start_num',
                'target_num',
                'steps'
            ]
        }
    ]
} as const;

export const QuestionAttributesColourPathSchema = {
    title: 'QuestionAttributesColourPath',
    description: 'A set of attributes for the ColourPath-style Question',
    allOf: [
        {
            $ref: '#/components/schemas/QuestionAttributesCore'
        },
        {
            type: 'object',
            additionalProperties: false,
            properties: {
                grid_width: {
                    type: 'integer',
                    format: 'int32',
                    minimum: 4,
                    maximum: 25,
                    readOnly: true
                },
                grid_height: {
                    type: 'integer',
                    format: 'int32',
                    minimum: 4,
                    maximum: 25,
                    readOnly: true
                },
                number_of_colours: {
                    type: 'integer',
                    format: 'int32',
                    minimum: 2,
                    maximum: 10,
                    readOnly: true
                }
            }
        }
    ]
} as const;

export const linksCurrentQuestionSchema = {
    type: 'object',
    title: 'linksCurrentQuestion',
    description: 'Links to related questions for traversing the assessment',
    additionalProperties: false,
    properties: {
        first: {
            type: 'string',
            description: 'To be explicit always include the field, but set to null if not applicable.',
            format: 'uri',
            maxLength: 190,
            readOnly: true
        },
        prev: {
            type: 'string',
            description: 'To be explicit always include the field, but set to null if not applicable.',
            format: 'uri',
            maxLength: 190,
            readOnly: true
        },
        next: {
            type: 'string',
            description: 'To be explicit always include the field, but set to null if not applicable.',
            format: 'uri',
            maxLength: 190,
            readOnly: true
        }
    },
    required: [
        'first',
        'prev',
        'next'
    ]
} as const;

export const AnswerOptionSchema = {
    type: 'object',
    title: 'AnswerOption',
    description: 'A possible answer/response to a Question',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'answer-options',
            default: 'answer-options'
        },
        attributes: {
            type: 'object',
            additionalProperties: false,
            properties: {
                text: {
                    type: 'string',
                    format: 'regex',
                    pattern: '^[\\w\\s\\d\\p{P}\\r\\n]+',
                    maxLength: 190,
                    readOnly: true
                },
                image_url: {
                    type: 'string',
                    format: 'uri',
                    maxLength: 190,
                    readOnly: true
                }
            }
        },
        relationships: {
            type: 'object',
            additionalProperties: false,
            properties: {
                question: {
                    $ref: '#/components/schemas/relationshipQuestion'
                }
            }
        }
    },
    required: [
        'id',
        'type',
        'attributes'
    ]
} as const;

export const AnswerFreeTextWritableSchema = {
    type: 'object',
    title: 'AnswerFreeText',
    description: 'A free-text Answer supplied by a Candidate',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'answers',
            default: 'answers'
        },
        attributes: {
            type: 'object',
            additionalProperties: false,
            properties: {
                answer: {
                    type: 'string',
                    pattern: '^[\\w\\s\\d\\p{P}\\r\\n]+',
                    minLength: 1,
                    maxLength: 190
                }
            }
        },
        relationships: {
            type: 'object',
            additionalProperties: false,
            properties: {
                candidate_assessment: {
                    $ref: '#/components/schemas/relationshipCandidateAssessmentWritable'
                },
                question: {
                    $ref: '#/components/schemas/relationshipQuestionWritable'
                }
            },
            required: [
                'candidate_assessment',
                'question'
            ]
        }
    },
    required: [
        'id',
        'type',
        'attributes',
        'relationships'
    ]
} as const;

export const relationshipCandidateAssessmentWritableSchema = {
    type: 'object',
    title: 'relationshipCandidateAssessment',
    description: 'CandidateAssessment relationship object',
    additionalProperties: false,
    properties: {
        data: {
            type: 'object',
            additionalProperties: false,
            properties: {
                id: {
                    $ref: '#/components/schemas/resourceId'
                }
            },
            required: [
                'id'
            ]
        }
    },
    required: [
        'data'
    ]
} as const;

export const relationshipQuestionWritableSchema = {
    type: 'object',
    title: 'relationshipQuestion',
    description: 'Question relationship object',
    additionalProperties: false,
    properties: {
        data: {
            type: 'object',
            additionalProperties: false,
            properties: {
                id: {
                    $ref: '#/components/schemas/resourceId'
                }
            },
            required: [
                'id'
            ]
        }
    },
    required: [
        'data'
    ]
} as const;

export const AnswerRelationshipAnswerOptionWritableSchema = {
    type: 'object',
    title: 'AnswerRelationshipAnswerOption',
    description: 'An AnswerOption selected by a Candidate',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'answers',
            default: 'answers'
        },
        relationships: {
            type: 'object',
            additionalProperties: false,
            properties: {
                candidate_assessment: {
                    $ref: '#/components/schemas/relationshipCandidateAssessmentWritable'
                },
                answer_option: {
                    $ref: '#/components/schemas/relationshipAnswerOptionWritable'
                },
                question: {
                    $ref: '#/components/schemas/relationshipQuestionWritable'
                }
            },
            required: [
                'candidate_assessment',
                'answer_option',
                'question'
            ]
        }
    },
    required: [
        'id',
        'type',
        'relationships'
    ]
} as const;

export const relationshipAnswerOptionWritableSchema = {
    type: 'object',
    title: 'relationshipAnswerOption',
    description: 'AnswerOption relationship object',
    additionalProperties: false,
    properties: {
        data: {
            type: 'object',
            additionalProperties: false,
            properties: {
                id: {
                    $ref: '#/components/schemas/resourceId'
                }
            },
            required: [
                'id'
            ]
        }
    },
    required: [
        'data'
    ]
} as const;

export const CandidateWritableSchema = {
    type: 'object',
    title: 'Candidate',
    description: 'Person who completes a CandidateAssessment.',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId',
            description: 'Unique identifier for the given candidate.'
        },
        type: {
            const: 'candidates',
            default: 'candidates'
        },
        attributes: {
            type: 'object',
            additionalProperties: false,
            properties: {
                first_name: {
                    type: 'string',
                    format: 'regex',
                    pattern: '^[A-Za-z -_]+',
                    maxLength: 190
                },
                surname: {
                    type: 'string',
                    format: 'regex',
                    pattern: '^[A-Za-z -_]+',
                    maxLength: 190
                },
                email: {
                    type: 'string',
                    format: 'email',
                    maxLength: 190
                },
                email_verified: {
                    type: 'boolean',
                    description: 'Set to true if the candidate\'s email has been verified.'
                },
                external_reference: {
                    type: [
                        'string',
                        'null'
                    ],
                    description: 'A reference you can use to link with a candidate in another system.',
                    format: 'regex',
                    pattern: '^[A-Za-z0-9 -_\\.]+',
                    maxLength: 190
                },
                gdpr_approval_date: {
                    type: 'string',
                    format: 'date-time',
                    maxLength: 50
                }
            },
            required: [
                'first_name',
                'surname',
                'email'
            ]
        }
    },
    required: [
        'id',
        'type',
        'attributes'
    ],
    examples: [
        {
            id: '142',
            first_name: 'Alice',
            surname: 'Smith',
            email: 'alice.smith@gmail.com',
            email_verified: true,
            created_at: '2018-01-01T12:00:00.000Z',
            updated_at: '2018-01-01T12:00:00.000Z',
            external_reference: 'Q705'
        }
    ]
} as const;

export const AssessmentWritableSchema = {
    type: 'object',
    title: 'Assessment',
    description: 'Test template from which a CandidateAssessment is created.',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'assessments',
            default: 'assessments'
        },
        attributes: {
            type: 'object',
            additionalProperties: false,
            properties: {
                language: {
                    $ref: '#/components/schemas/Language'
                },
                conclusion: {
                    type: [
                        'string',
                        'null'
                    ],
                    pattern: '^[\\w\\s\\d\\p{P}\\r\\n]+',
                    maxLength: 2500
                }
            }
        }
    },
    required: [
        'id',
        'type',
        'attributes'
    ]
} as const;

export const CandidateAssessmentWritableSchema = {
    type: 'object',
    title: 'CandidateAssessment',
    description: 'An Assessment assigned to a Candidate.',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'candidate-assessments',
            default: 'candidate-assessments'
        },
        attributes: {
            type: 'object',
            additionalProperties: false
        },
        relationships: {
            type: 'object',
            additionalProperties: false,
            properties: {
                candidate: {
                    $ref: '#/components/schemas/relationshipCandidateWritable'
                },
                assessment: {
                    $ref: '#/components/schemas/relationshipAssessmentWritable'
                }
            }
        },
        links: {
            type: 'object',
            additionalProperties: false
        }
    },
    required: [
        'id',
        'type',
        'attributes'
    ]
} as const;

export const relationshipCandidateWritableSchema = {
    type: 'object',
    title: 'relationshipCandidate',
    description: 'Candidate relationship object',
    additionalProperties: false,
    properties: {
        data: {
            type: 'object',
            additionalProperties: false,
            properties: {
                id: {
                    $ref: '#/components/schemas/resourceId'
                }
            },
            required: [
                'id'
            ]
        }
    },
    required: [
        'data'
    ]
} as const;

export const relationshipAssessmentWritableSchema = {
    type: 'object',
    title: 'relationshipAssessment',
    description: 'Assessment relationship object',
    additionalProperties: false,
    properties: {
        data: {
            type: 'object',
            additionalProperties: false,
            properties: {
                id: {
                    $ref: '#/components/schemas/resourceId'
                }
            },
            required: [
                'id'
            ]
        }
    },
    required: [
        'data'
    ]
} as const;

export const ScoreSetWritableSchema = {
    type: 'object',
    title: 'ScoreSet',
    description: 'A set of scores for a CandidateAssessment.',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        attributes: {
            type: 'object',
            additionalProperties: false
        },
        relationships: {
            type: 'object',
            additionalProperties: false,
            properties: {
                candidate_assessments: {
                    $ref: '#/components/schemas/relationshipCandidateAssessmentWritable'
                }
            }
        }
    },
    required: [
        'id',
        'attributes'
    ]
} as const;

export const ReportWritableSchema = {
    type: 'object',
    title: 'Report',
    description: 'Easy-to-read results of an Assessment.',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'reports',
            default: 'reports'
        },
        attributes: {
            type: 'object',
            additionalProperties: false
        }
    },
    required: [
        'id',
        'type',
        'attributes'
    ]
} as const;

export const QuestionWritableSchema = {
    type: 'object',
    title: 'Question',
    description: 'An item on an Assessment that offers one or more AnswerOptions',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'questions',
            default: 'questions'
        },
        attributes: {
            oneOf: [
                {
                    $ref: '#/components/schemas/QuestionAttributesBasicWritable'
                },
                {
                    $ref: '#/components/schemas/QuestionAttributesNumberPathWritable'
                },
                {
                    $ref: '#/components/schemas/QuestionAttributesColourPathWritable'
                }
            ]
        },
        relationships: {
            type: 'object',
            additionalProperties: false
        }
    },
    required: [
        'id',
        'type',
        'attributes'
    ]
} as const;

export const QuestionAttributesBasicWritableSchema = {
    title: 'QuestionAttributesBasic',
    description: 'A set of attributes used in basic questions',
    allOf: [
        {
            $ref: '#/components/schemas/QuestionAttributesCoreWritable'
        },
        {
            type: 'object',
            additionalProperties: false
        }
    ]
} as const;

export const QuestionAttributesCoreWritableSchema = {
    type: 'object',
    title: 'QuestionAttributesCore',
    description: 'A set of attributes shared by all Questions',
    additionalProperties: false,
    properties: {
        language: {
            $ref: '#/components/schemas/Language'
        }
    }
} as const;

export const QuestionAttributesNumberPathWritableSchema = {
    title: 'QuestionAttributesNumberPath',
    description: 'A set of attributes for the NumberPath-style Question',
    examples: [
        {
            id: '497f6eca-6276-4993-bfeb-53cbbbba6f08',
            type: 'questions',
            attributes: {
                type: 'NUMBER_PATH',
                text: 'Match the target number to the start number to win.',
                language: 'en',
                answer_order: 'RANDOM'
            },
            relationships: {},
            start_num: 1,
            target_num: 10,
            steps: [
                {
                    step_num: 1,
                    step_options: [
                        {
                            option_label: '+ 1',
                            option_operator: 'ADD',
                            option_value: 1
                        },
                        {
                            option_label: '+ 2',
                            option_operator: 'ADD',
                            option_value: 2
                        },
                        {
                            option_label: '+ 3',
                            option_operator: 'ADD',
                            option_value: 3
                        },
                        {
                            option_label: '+ 4',
                            option_operator: 'ADD',
                            option_value: 4
                        }
                    ]
                },
                {
                    step_num: 2,
                    step_options: [
                        {
                            option_label: 'x 2',
                            option_operator: 'MULTIPLY',
                            option_value: 2
                        },
                        {
                            option_label: '- 1',
                            option_operator: 'SUBTRACT',
                            option_value: 1
                        },
                        {
                            option_label: '/ 2',
                            option_operator: 'DIVIDE',
                            option_value: 2
                        },
                        {
                            option_label: '+ 3',
                            option_operator: 'ADD',
                            option_value: 3
                        }
                    ]
                },
                {
                    step_num: 3,
                    step_options: [
                        {
                            optionLabel: '- 1',
                            option_operator: 'SUBTRACT',
                            option_value: 1
                        },
                        {
                            optionLabel: '- 2',
                            option_operator: 'SUBTRACT',
                            option_value: 2
                        },
                        {
                            optionLabel: '- 3',
                            option_operator: 'SUBTRACT',
                            option_value: 3
                        },
                        {
                            optionLabel: '- 4',
                            option_operator: 'SUBTRACT',
                            option_value: 4
                        }
                    ]
                }
            ]
        }
    ],
    allOf: [
        {
            $ref: '#/components/schemas/QuestionAttributesCoreWritable'
        },
        {
            type: 'object',
            additionalProperties: false,
            properties: {
                steps: {
                    type: 'array',
                    minItems: 1,
                    maxItems: 25,
                    items: {
                        type: 'object',
                        additionalProperties: false,
                        properties: {
                            step_options: {
                                type: 'array',
                                minItems: 1,
                                maxItems: 10,
                                items: {
                                    type: 'object',
                                    additionalProperties: false
                                }
                            }
                        },
                        required: [
                            'step_options'
                        ]
                    }
                }
            },
            required: [
                'steps'
            ]
        }
    ]
} as const;

export const QuestionAttributesColourPathWritableSchema = {
    title: 'QuestionAttributesColourPath',
    description: 'A set of attributes for the ColourPath-style Question',
    allOf: [
        {
            $ref: '#/components/schemas/QuestionAttributesCoreWritable'
        },
        {
            type: 'object',
            additionalProperties: false
        }
    ]
} as const;

export const AnswerOptionWritableSchema = {
    type: 'object',
    title: 'AnswerOption',
    description: 'A possible answer/response to a Question',
    additionalProperties: false,
    properties: {
        id: {
            $ref: '#/components/schemas/resourceId'
        },
        type: {
            const: 'answer-options',
            default: 'answer-options'
        },
        attributes: {
            type: 'object',
            additionalProperties: false
        },
        relationships: {
            type: 'object',
            additionalProperties: false,
            properties: {
                question: {
                    $ref: '#/components/schemas/relationshipQuestionWritable'
                }
            }
        }
    },
    required: [
        'id',
        'type',
        'attributes'
    ]
} as const;
