// This file is auto-generated by @hey-api/openapi-ts

import type { GetCandidateAssessmentsCandidateAssessmentIdReportsResponse, GetCandidateAssessmentsCandidateAssessmentIdResponse, GetCandidatesCandidateIdCandidateAssessmentsResponse, GetCandidatesCandidateIdResponse, GetCandidatesResponse, PatchCandidatesCandidateIdResponse, PostCandidateAssessmentsResponse, PostCandidatesResponse } from './types.gen';

const candidateSchemaResponseTransformer = (data: any) => {
    if (data.attributes.created_at) {
        data.attributes.created_at = new Date(data.attributes.created_at);
    }
    if (data.attributes.updated_at) {
        data.attributes.updated_at = new Date(data.attributes.updated_at);
    }
    if (data.attributes.gdpr_approval_date) {
        data.attributes.gdpr_approval_date = new Date(data.attributes.gdpr_approval_date);
    }
    return data;
};

export const getCandidatesResponseTransformer = async (data: any): Promise<GetCandidatesResponse> => {
    data.data = data.data.map((item: any) => candidateSchemaResponseTransformer(item));
    return data;
};

export const postCandidatesResponseTransformer = async (data: any): Promise<PostCandidatesResponse> => {
    data.data = candidateSchemaResponseTransformer(data.data);
    return data;
};

export const getCandidatesCandidateIdResponseTransformer = async (data: any): Promise<GetCandidatesCandidateIdResponse> => {
    data.data = candidateSchemaResponseTransformer(data.data);
    return data;
};

export const patchCandidatesCandidateIdResponseTransformer = async (data: any): Promise<PatchCandidatesCandidateIdResponse> => {
    data.data = candidateSchemaResponseTransformer(data.data);
    return data;
};

const candidateAssessmentSchemaResponseTransformer = (data: any) => {
    if (data.attributes.created_at) {
        data.attributes.created_at = new Date(data.attributes.created_at);
    }
    if (data.attributes.updated_at) {
        data.attributes.updated_at = new Date(data.attributes.updated_at);
    }
    if (data.attributes.started_at) {
        data.attributes.started_at = new Date(data.attributes.started_at);
    }
    if (data.attributes.completed_at) {
        data.attributes.completed_at = new Date(data.attributes.completed_at);
    }
    return data;
};

export const getCandidatesCandidateIdCandidateAssessmentsResponseTransformer = async (data: any): Promise<GetCandidatesCandidateIdCandidateAssessmentsResponse> => {
    data.data = data.data.map((item: any) => candidateAssessmentSchemaResponseTransformer(item));
    return data;
};

export const postCandidateAssessmentsResponseTransformer = async (data: any): Promise<PostCandidateAssessmentsResponse> => {
    data.data = candidateAssessmentSchemaResponseTransformer(data.data);
    return data;
};

export const getCandidateAssessmentsCandidateAssessmentIdResponseTransformer = async (data: any): Promise<GetCandidateAssessmentsCandidateAssessmentIdResponse> => {
    data.data = candidateAssessmentSchemaResponseTransformer(data.data);
    return data;
};

const reportSchemaResponseTransformer = (data: any) => {
    if (data.attributes.created_at) {
        data.attributes.created_at = new Date(data.attributes.created_at);
    }
    if (data.attributes.updated_at) {
        data.attributes.updated_at = new Date(data.attributes.updated_at);
    }
    return data;
};

export const getCandidateAssessmentsCandidateAssessmentIdReportsResponseTransformer = async (data: any): Promise<GetCandidateAssessmentsCandidateAssessmentIdReportsResponse> => {
    data.data = data.data.map((item: any) => reportSchemaResponseTransformer(item));
    return data;
};
