// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | 'https://www.viewpoint-psychology.com/api/v1' | 'https://api.itesthub.com/v1' | (string & {});
};

/**
 * AnswerFreeText
 *
 * A free-text Answer supplied by a Candidate
 */
export type AnswerFreeText = {
    id?: ResourceId;
    type: 'answers';
    attributes: {
        answer?: string;
    };
    relationships: {
        candidate_assessment: RelationshipCandidateAssessment;
        question: RelationshipQuestion;
    };
};

/**
 * resourceId
 *
 * Resource ID.
 */
export type ResourceId = string;

/**
 * relationshipCandidateAssessment
 *
 * CandidateAssessment relationship object
 */
export type RelationshipCandidateAssessment = {
    data: {
        readonly type: 'candidate-assessments';
        id: ResourceId;
    };
};

/**
 * relationshipQuestion
 *
 * Question relationship object
 */
export type RelationshipQuestion = {
    data: {
        readonly type: 'questions';
        id: ResourceId;
    };
};

/**
 * AnswerRelationshipAnswerOption
 *
 * An AnswerOption selected by a Candidate
 */
export type AnswerRelationshipAnswerOption = {
    id?: ResourceId;
    type: 'answers';
    relationships: {
        candidate_assessment: RelationshipCandidateAssessment;
        answer_option: RelationshipAnswerOption;
        question: RelationshipQuestion;
    };
};

/**
 * relationshipAnswerOption
 *
 * AnswerOption relationship object
 */
export type RelationshipAnswerOption = {
    data: {
        readonly type: 'answer-options';
        id: ResourceId;
    };
};

/**
 * Candidate
 *
 * Person who completes a CandidateAssessment.
 */
export type Candidate = {
    /**
     * Unique identifier for the given candidate.
     */
    id?: ResourceId;
    type: 'candidates';
    attributes: {
        first_name: string;
        surname: string;
        email: string;
        /**
         * Set to true if the candidate's email has been verified.
         */
        email_verified?: boolean;
        /**
         * Timestamp for record creation.
         */
        readonly created_at?: Date;
        /**
         * Timestamp for last update.
         */
        readonly updated_at?: Date | null;
        /**
         * A reference you can use to link with a candidate in another system.
         */
        external_reference?: string | null;
        gdpr_approval_date?: Date;
    };
};

/**
 * CandidateAssessmentAction
 *
 * An Action resource for a CandidateAssessment.
 */
export type CandidateAssessmentAction = {
    id?: ResourceId;
    type: 'candidate-assessment-actions';
    attributes: {
        action: 'start' | 'finish';
    };
    relationships: {
        'candidate-assessment': RelationshipCandidateAssessment;
    };
};

/**
 * Error
 *
 * Standard error object in a response.
 */
export type Error = {
    readonly title: string;
    readonly detail: string;
    readonly code: string;
    readonly status: number;
};

/**
 * metaCollectionPagination
 *
 * Standard pagination object in a meta response object.
 */
export type MetaCollectionPagination = {
    readonly resource_count: number;
    readonly page_count: number;
};

/**
 * linksCollectionPagination
 *
 * Object in a response that provides pagination Links
 */
export type LinksCollectionPagination = {
    /**
     * To be explicit always include the field, but set to null if not applicable.
     */
    readonly first: string;
    /**
     * To be explicit always include the field, but set to null if not applicable.
     */
    readonly next?: string;
    /**
     * To be explicit always include the field, but set to null if not applicable.
     */
    readonly prev?: string;
    /**
     * To be explicit always include the field, but set to null if not applicable.
     */
    readonly last?: string;
};

/**
 * Assessment
 *
 * Test template from which a CandidateAssessment is created.
 */
export type Assessment = {
    id: ResourceId;
    type: 'assessments';
    attributes: {
        readonly type: string;
        readonly title: string;
        language?: Language;
        readonly description?: string | null;
        readonly time_limit?: string | null;
        readonly introduction?: string | null;
        conclusion?: string | null;
    };
};

/**
 * Language
 *
 * ISO 639-1. Possibly 639:2023 when available.
 */
export const Language = {
    EN: 'en',
    ES: 'es',
    FR: 'fr',
    DE: 'de'
} as const;

/**
 * Language
 *
 * ISO 639-1. Possibly 639:2023 when available.
 */
export type Language = typeof Language[keyof typeof Language];

/**
 * CandidateAssessment
 *
 * An Assessment assigned to a Candidate.
 */
export type CandidateAssessment = {
    id?: ResourceId;
    type: 'candidate-assessments';
    attributes: {
        readonly url: string;
        readonly created_at?: Date;
        readonly updated_at?: Date | null;
        readonly started_at?: Date | null;
        readonly completed_at?: Date | null;
    };
    relationships?: {
        candidate?: RelationshipCandidate;
        assessment?: RelationshipAssessment;
    };
    links?: {
        readonly current_question?: string;
    };
};

/**
 * relationshipCandidate
 *
 * Candidate relationship object
 */
export type RelationshipCandidate = {
    data: {
        readonly type: 'candidates';
        id: ResourceId;
    };
};

/**
 * relationshipAssessment
 *
 * Assessment relationship object
 */
export type RelationshipAssessment = {
    data: {
        readonly type: 'assessments';
        id: ResourceId;
    };
};

/**
 * ScoreSet
 *
 * A set of scores for a CandidateAssessment.
 */
export type ScoreSet = {
    id: ResourceId;
    readonly type: 'score-sets';
    attributes: {
        readonly behavioural_scores?: Array<{
            readonly name: string;
            readonly score: number;
        }>;
        readonly overall_score: number;
    };
    relationships?: {
        'candidate-assessments'?: RelationshipCandidateAssessment;
    };
};

/**
 * Report
 *
 * Easy-to-read results of an Assessment.
 */
export type Report = {
    id: ResourceId;
    type: 'reports';
    attributes: {
        readonly title: string;
        readonly description?: string;
        readonly created_at?: Date;
        readonly updated_at?: Date | null;
    };
};

/**
 * Question
 *
 * An item on an Assessment that offers one or more AnswerOptions
 */
export type Question = {
    id: ResourceId;
    type: 'questions';
    attributes: QuestionAttributesBasic | QuestionAttributesNumberPath | QuestionAttributesColourPath;
};

/**
 * QuestionAttributesBasic
 *
 * A set of attributes used in a basic Question
 */
export type QuestionAttributesBasic = QuestionAttributesCore & {
    readonly text?: string;
    readonly image_url?: string;
    readonly additional_answer_options?: Array<'SKIP' | 'NOT_APPLICABLE'>;
};

/**
 * QuestionAttributesCore
 *
 * A set of attributes shared by all Questions
 */
export type QuestionAttributesCore = {
    question_type: 'SJT_MOST2' | 'SJT_MOST3' | 'SJT_MOST_LEAST' | 'SORTING' | 'VERBAL_HORIZONTAL' | 'VERBAL_VERTICAL' | 'NUMERICAL_HORIZONTAL' | 'NUMERICAL_VERTICAL' | 'NUMBER_PATH';
    language?: Language;
    /**
     * Possibly future options of ALPHA_ASC, etc.
     */
    answer_order?: 'RANDOM' | 'STATIC';
    readonly answer_required?: boolean;
};

/**
 * QuestionAttributesNumberPath
 *
 * A set of attributes for the NumberPath-style Question
 */
export type QuestionAttributesNumberPath = QuestionAttributesCore & {
    readonly start_num: number;
    readonly target_num: number;
    steps: Array<{
        readonly step_num: number;
        step_options: Array<{
            readonly option_label?: string;
            option_operator: 'ADD' | 'SUBTRACT' | 'MULTIPLY' | 'DIVIDE' | 'POWER' | 'ROOT';
            readonly option_operand: number;
        }>;
    }>;
};

/**
 * QuestionAttributesColourPath
 *
 * A set of attributes for the ColourPath-style Question
 */
export type QuestionAttributesColourPath = QuestionAttributesCore & {
    readonly grid_width?: number;
    readonly grid_height?: number;
    readonly number_of_colours?: number;
};

/**
 * linksCurrentQuestion
 *
 * Links to related Questions for traversing the Assessment
 */
export type LinksCurrentQuestion = {
    /**
     * To be explicit always include the field, but set to null if not applicable.
     */
    readonly first: string;
    /**
     * To be explicit always include the field, but set to null if not applicable.
     */
    readonly prev: string;
    /**
     * To be explicit always include the field, but set to null if not applicable.
     */
    readonly next: string;
};

/**
 * AnswerOption
 *
 * A possible answer/response to a Question
 */
export type AnswerOption = {
    id: ResourceId;
    type: 'answer-options';
    attributes: {
        readonly text?: string;
        readonly image_url?: string;
    };
    relationships?: {
        question?: RelationshipQuestion;
    };
};

/**
 * AnswerFreeText
 *
 * A free-text Answer supplied by a Candidate
 */
export type AnswerFreeTextWritable = {
    id?: ResourceId;
    type: 'answers';
    attributes: {
        answer?: string;
    };
    relationships: {
        candidate_assessment: RelationshipCandidateAssessmentWritable;
        question: RelationshipQuestionWritable;
    };
};

/**
 * relationshipCandidateAssessment
 *
 * CandidateAssessment relationship object
 */
export type RelationshipCandidateAssessmentWritable = {
    data: {
        id: ResourceId;
    };
};

/**
 * relationshipQuestion
 *
 * Question relationship object
 */
export type RelationshipQuestionWritable = {
    data: {
        id: ResourceId;
    };
};

/**
 * AnswerRelationshipAnswerOption
 *
 * An AnswerOption selected by a Candidate
 */
export type AnswerRelationshipAnswerOptionWritable = {
    id?: ResourceId;
    type: 'answers';
    relationships: {
        candidate_assessment: RelationshipCandidateAssessmentWritable;
        answer_option: RelationshipAnswerOptionWritable;
        question: RelationshipQuestionWritable;
    };
};

/**
 * relationshipAnswerOption
 *
 * AnswerOption relationship object
 */
export type RelationshipAnswerOptionWritable = {
    data: {
        id: ResourceId;
    };
};

/**
 * Candidate
 *
 * Person who completes a CandidateAssessment.
 */
export type CandidateWritable = {
    /**
     * Unique identifier for the given candidate.
     */
    id?: ResourceId;
    type: 'candidates';
    attributes: {
        first_name: string;
        surname: string;
        email: string;
        /**
         * Set to true if the candidate's email has been verified.
         */
        email_verified?: boolean;
        /**
         * A reference you can use to link with a candidate in another system.
         */
        external_reference?: string | null;
        gdpr_approval_date?: Date;
    };
};

/**
 * CandidateAssessmentAction
 *
 * An Action resource for a CandidateAssessment.
 */
export type CandidateAssessmentActionWritable = {
    id?: ResourceId;
    type: 'candidate-assessment-actions';
    attributes: {
        action: 'start' | 'finish';
    };
    relationships: {
        'candidate-assessment': RelationshipCandidateAssessmentWritable;
    };
};

/**
 * Assessment
 *
 * Test template from which a CandidateAssessment is created.
 */
export type AssessmentWritable = {
    id: ResourceId;
    type: 'assessments';
    attributes: {
        language?: Language;
        conclusion?: string | null;
    };
};

/**
 * CandidateAssessment
 *
 * An Assessment assigned to a Candidate.
 */
export type CandidateAssessmentWritable = {
    id?: ResourceId;
    type: 'candidate-assessments';
    attributes: {
        [key: string]: never;
    };
    relationships?: {
        candidate?: RelationshipCandidateWritable;
        assessment?: RelationshipAssessmentWritable;
    };
    links?: {
        [key: string]: never;
    };
};

/**
 * relationshipCandidate
 *
 * Candidate relationship object
 */
export type RelationshipCandidateWritable = {
    data: {
        id: ResourceId;
    };
};

/**
 * relationshipAssessment
 *
 * Assessment relationship object
 */
export type RelationshipAssessmentWritable = {
    data: {
        id: ResourceId;
    };
};

/**
 * ScoreSet
 *
 * A set of scores for a CandidateAssessment.
 */
export type ScoreSetWritable = {
    id: ResourceId;
    attributes: {
        [key: string]: never;
    };
    relationships?: {
        'candidate-assessments'?: RelationshipCandidateAssessmentWritable;
    };
};

/**
 * Report
 *
 * Easy-to-read results of an Assessment.
 */
export type ReportWritable = {
    id: ResourceId;
    type: 'reports';
    attributes: {
        [key: string]: never;
    };
};

/**
 * Question
 *
 * An item on an Assessment that offers one or more AnswerOptions
 */
export type QuestionWritable = {
    id: ResourceId;
    type: 'questions';
    attributes: QuestionAttributesBasicWritable | QuestionAttributesNumberPathWritable | QuestionAttributesColourPathWritable;
};

/**
 * QuestionAttributesBasic
 *
 * A set of attributes used in a basic Question
 */
export type QuestionAttributesBasicWritable = QuestionAttributesCoreWritable & {};

/**
 * QuestionAttributesCore
 *
 * A set of attributes shared by all Questions
 */
export type QuestionAttributesCoreWritable = {
    language?: Language;
};

/**
 * QuestionAttributesNumberPath
 *
 * A set of attributes for the NumberPath-style Question
 */
export type QuestionAttributesNumberPathWritable = QuestionAttributesCoreWritable & {
    steps: Array<{
        step_options: Array<{}>;
    }>;
};

/**
 * QuestionAttributesColourPath
 *
 * A set of attributes for the ColourPath-style Question
 */
export type QuestionAttributesColourPathWritable = QuestionAttributesCoreWritable & {};

/**
 * AnswerOption
 *
 * A possible answer/response to a Question
 */
export type AnswerOptionWritable = {
    id: ResourceId;
    type: 'answer-options';
    attributes: {
        [key: string]: never;
    };
    relationships?: {
        question?: RelationshipQuestionWritable;
    };
};

/**
 * page[size] and/or page[number] for pagination.
 */
export type Page = Array<unknown>;

/**
 * Unique ID of a Candidate
 */
export type CandidateId = string;

/**
 * Unique ID of a CandidateAssessment
 */
export type CandidateAssessmentId = string;

/**
 * Unique ID of a Report
 */
export type ReportId = string;

/**
 * Unique ID of an Assessment
 */
export type AssessmentId = string;

/**
 * Unique ID of a CandidateReport
 */
export type CandidateReportId = string;

/**
 * Unique ID of a Question
 */
export type QuestionId = string;

/**
 * Unique ID of an Answer
 */
export type AnswerId = string;

/**
 * Unique ID of an AnswerOption
 */
export type AnswerOptionId = string;

export type AnswerCreateOrUpdate = {
    data: AnswerFreeTextWritable | AnswerRelationshipAnswerOptionWritable;
};

export type CandidateCreate = {
    data: CandidateWritable;
};

export type CandidateUpdate = {
    data: CandidateWritable;
};

export type CandidateAssessmentCreate = {
    data: {
        type: 'candidate-assessments';
        attributes: {
            [key: string]: never;
        };
    };
    relationships: {
        candidate: {
            data: {
                type: 'candidates';
                id: ResourceId;
            };
        };
        assessment: {
            data: {
                type: 'assessments';
                id: ResourceId;
            };
        };
    };
};

export type CandidateAssessmentUpdate = {
    data: {
        type: 'candidate-assessments';
        id: ResourceId;
        attributes?: {
            [key: string]: never;
        };
    };
};

export type CandidateAssessmentActionCreate = {
    data: CandidateAssessmentActionWritable;
};

export type PostAnswersData = {
    body?: AnswerCreateOrUpdate;
    path?: never;
    query?: never;
    url: '/answers';
};

export type PostAnswersErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type PostAnswersError = PostAnswersErrors[keyof PostAnswersErrors];

export type PostAnswersResponses = {
    /**
     * Single Answer
     */
    201: {
        data: AnswerFreeText | AnswerRelationshipAnswerOption;
    };
};

export type PostAnswersResponse = PostAnswersResponses[keyof PostAnswersResponses];

export type PatchAnswersAnswerIdData = {
    body?: AnswerCreateOrUpdate;
    path: {
        /**
         * Unique ID of an Answer
         */
        answerId: string;
    };
    query?: never;
    url: '/answers/{answerId}';
};

export type PatchAnswersAnswerIdErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * The 404 (Not Found) status code indicates that the origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
     */
    404: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type PatchAnswersAnswerIdError = PatchAnswersAnswerIdErrors[keyof PatchAnswersAnswerIdErrors];

export type PatchAnswersAnswerIdResponses = {
    /**
     * Single Answer
     */
    200: {
        data: AnswerFreeText | AnswerRelationshipAnswerOption;
    };
};

export type PatchAnswersAnswerIdResponse = PatchAnswersAnswerIdResponses[keyof PatchAnswersAnswerIdResponses];

export type GetAssessmentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * page[size] and/or page[number] for pagination.
         */
        page?: Array<unknown>;
    };
    url: '/assessments';
};

export type GetAssessmentsErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type GetAssessmentsError = GetAssessmentsErrors[keyof GetAssessmentsErrors];

export type GetAssessmentsResponses = {
    /**
     * Collection of Assessments.
     */
    200: {
        data: Array<Assessment>;
        meta: MetaCollectionPagination;
        links?: {
            pagination: LinksCollectionPagination;
        };
    };
};

export type GetAssessmentsResponse = GetAssessmentsResponses[keyof GetAssessmentsResponses];

export type GetAssessmentsAssessmentIdData = {
    body?: never;
    path: {
        /**
         * Unique ID of an Assessment
         */
        assessmentId: string;
    };
    query?: never;
    url: '/assessments/{assessmentId}';
};

export type GetAssessmentsAssessmentIdErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * The 404 (Not Found) status code indicates that the origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
     */
    404: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type GetAssessmentsAssessmentIdError = GetAssessmentsAssessmentIdErrors[keyof GetAssessmentsAssessmentIdErrors];

export type GetAssessmentsAssessmentIdResponses = {
    /**
     * Single Assessment
     */
    200: {
        data: Assessment;
    };
};

export type GetAssessmentsAssessmentIdResponse = GetAssessmentsAssessmentIdResponses[keyof GetAssessmentsAssessmentIdResponses];

export type GetCandidatesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * page[size] and/or page[number] for pagination.
         */
        page?: Array<unknown>;
    };
    url: '/candidates';
};

export type GetCandidatesErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type GetCandidatesError = GetCandidatesErrors[keyof GetCandidatesErrors];

export type GetCandidatesResponses = {
    /**
     * Collection of Candidates.
     */
    200: {
        data: Array<Candidate>;
        meta: MetaCollectionPagination;
        links?: {
            pagination: LinksCollectionPagination;
        };
    };
};

export type GetCandidatesResponse = GetCandidatesResponses[keyof GetCandidatesResponses];

export type PostCandidatesData = {
    body?: CandidateCreate;
    path?: never;
    query?: never;
    url: '/candidates';
};

export type PostCandidatesErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type PostCandidatesError = PostCandidatesErrors[keyof PostCandidatesErrors];

export type PostCandidatesResponses = {
    /**
     * Single Candidate.
     */
    201: {
        data: Candidate;
    };
};

export type PostCandidatesResponse = PostCandidatesResponses[keyof PostCandidatesResponses];

export type GetCandidatesCandidateIdData = {
    body?: never;
    path: {
        /**
         * Unique ID of a Candidate
         */
        candidateId: string;
    };
    query?: never;
    url: '/candidates/{candidateId}';
};

export type GetCandidatesCandidateIdErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * The 404 (Not Found) status code indicates that the origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
     */
    404: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type GetCandidatesCandidateIdError = GetCandidatesCandidateIdErrors[keyof GetCandidatesCandidateIdErrors];

export type GetCandidatesCandidateIdResponses = {
    /**
     * Single Candidate.
     */
    200: {
        data: Candidate;
    };
};

export type GetCandidatesCandidateIdResponse = GetCandidatesCandidateIdResponses[keyof GetCandidatesCandidateIdResponses];

export type PatchCandidatesCandidateIdData = {
    body?: CandidateUpdate;
    path: {
        /**
         * Unique ID of a Candidate
         */
        candidateId: string;
    };
    query?: never;
    url: '/candidates/{candidateId}';
};

export type PatchCandidatesCandidateIdErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * The 404 (Not Found) status code indicates that the origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
     */
    404: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type PatchCandidatesCandidateIdError = PatchCandidatesCandidateIdErrors[keyof PatchCandidatesCandidateIdErrors];

export type PatchCandidatesCandidateIdResponses = {
    /**
     * Single Candidate.
     */
    200: {
        data: Candidate;
    };
};

export type PatchCandidatesCandidateIdResponse = PatchCandidatesCandidateIdResponses[keyof PatchCandidatesCandidateIdResponses];

export type GetCandidatesCandidateIdCandidateAssessmentsData = {
    body?: never;
    path: {
        /**
         * Unique ID of a Candidate
         */
        candidateId: string;
    };
    query?: {
        /**
         * page[size] and/or page[number] for pagination.
         */
        page?: Array<unknown>;
    };
    url: '/candidates/{candidateId}/candidate-assessments';
};

export type GetCandidatesCandidateIdCandidateAssessmentsErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type GetCandidatesCandidateIdCandidateAssessmentsError = GetCandidatesCandidateIdCandidateAssessmentsErrors[keyof GetCandidatesCandidateIdCandidateAssessmentsErrors];

export type GetCandidatesCandidateIdCandidateAssessmentsResponses = {
    /**
     * Collection of CandidateAssessments.
     */
    200: {
        data: Array<CandidateAssessment>;
        meta: MetaCollectionPagination;
        links?: {
            pagination: LinksCollectionPagination;
        };
    };
};

export type GetCandidatesCandidateIdCandidateAssessmentsResponse = GetCandidatesCandidateIdCandidateAssessmentsResponses[keyof GetCandidatesCandidateIdCandidateAssessmentsResponses];

export type PostCandidateAssessmentsData = {
    body?: CandidateAssessmentCreate;
    path?: never;
    query?: never;
    url: '/candidate-assessments';
};

export type PostCandidateAssessmentsErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type PostCandidateAssessmentsError = PostCandidateAssessmentsErrors[keyof PostCandidateAssessmentsErrors];

export type PostCandidateAssessmentsResponses = {
    /**
     * Single CandidateAssessment.
     */
    201: {
        data: CandidateAssessment;
    };
};

export type PostCandidateAssessmentsResponse = PostCandidateAssessmentsResponses[keyof PostCandidateAssessmentsResponses];

export type GetCandidateAssessmentsCandidateAssessmentIdData = {
    body?: never;
    path: {
        /**
         * Unique ID of a CandidateAssessment
         */
        candidateAssessmentId: string;
    };
    query?: never;
    url: '/candidate-assessments/{candidateAssessmentId}';
};

export type GetCandidateAssessmentsCandidateAssessmentIdErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * The 404 (Not Found) status code indicates that the origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
     */
    404: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type GetCandidateAssessmentsCandidateAssessmentIdError = GetCandidateAssessmentsCandidateAssessmentIdErrors[keyof GetCandidateAssessmentsCandidateAssessmentIdErrors];

export type GetCandidateAssessmentsCandidateAssessmentIdResponses = {
    /**
     * Single CandidateAssessment.
     */
    200: {
        data: CandidateAssessment;
    };
};

export type GetCandidateAssessmentsCandidateAssessmentIdResponse = GetCandidateAssessmentsCandidateAssessmentIdResponses[keyof GetCandidateAssessmentsCandidateAssessmentIdResponses];

export type PostCandidateAssessmentsCandidateAssessmentIdActionsData = {
    body?: CandidateAssessmentActionCreate;
    path: {
        /**
         * Unique ID of a CandidateAssessment
         */
        candidateAssessmentId: string;
    };
    query?: never;
    url: '/candidate-assessments/{candidateAssessmentId}/actions';
};

export type PostCandidateAssessmentsCandidateAssessmentIdActionsErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * The 404 (Not Found) status code indicates that the origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
     */
    404: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type PostCandidateAssessmentsCandidateAssessmentIdActionsError = PostCandidateAssessmentsCandidateAssessmentIdActionsErrors[keyof PostCandidateAssessmentsCandidateAssessmentIdActionsErrors];

export type PostCandidateAssessmentsCandidateAssessmentIdActionsResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetCandidateAssessmentsCandidateAssessmentIdAnswersData = {
    body?: never;
    path: {
        /**
         * Unique ID of a CandidateAssessment
         */
        candidateAssessmentId: string;
    };
    query?: {
        /**
         * page[size] and/or page[number] for pagination.
         */
        page?: Array<unknown>;
    };
    url: '/candidate-assessments/{candidateAssessmentId}/answers';
};

export type GetCandidateAssessmentsCandidateAssessmentIdAnswersErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type GetCandidateAssessmentsCandidateAssessmentIdAnswersError = GetCandidateAssessmentsCandidateAssessmentIdAnswersErrors[keyof GetCandidateAssessmentsCandidateAssessmentIdAnswersErrors];

export type GetCandidateAssessmentsCandidateAssessmentIdAnswersResponses = {
    /**
     * Collection of Answers
     */
    200: {
        data: Array<AnswerFreeText | AnswerRelationshipAnswerOption>;
        meta: MetaCollectionPagination;
        links?: {
            pagination: LinksCollectionPagination;
        };
    };
};

export type GetCandidateAssessmentsCandidateAssessmentIdAnswersResponse = GetCandidateAssessmentsCandidateAssessmentIdAnswersResponses[keyof GetCandidateAssessmentsCandidateAssessmentIdAnswersResponses];

export type GetCandidateAssessmentsCandidateAssessmentIdQuestionsData = {
    body?: never;
    path: {
        /**
         * Unique ID of a CandidateAssessment
         */
        candidateAssessmentId: string;
    };
    query?: {
        /**
         * page[size] and/or page[number] for pagination.
         */
        page?: Array<unknown>;
    };
    url: '/candidate-assessments/{candidateAssessmentId}/questions';
};

export type GetCandidateAssessmentsCandidateAssessmentIdQuestionsErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type GetCandidateAssessmentsCandidateAssessmentIdQuestionsError = GetCandidateAssessmentsCandidateAssessmentIdQuestionsErrors[keyof GetCandidateAssessmentsCandidateAssessmentIdQuestionsErrors];

export type GetCandidateAssessmentsCandidateAssessmentIdQuestionsResponses = {
    /**
     * Collection of Questions
     */
    200: {
        data: Array<Question>;
        meta: MetaCollectionPagination;
        links?: {
            pagination: LinksCollectionPagination;
        };
    };
};

export type GetCandidateAssessmentsCandidateAssessmentIdQuestionsResponse = GetCandidateAssessmentsCandidateAssessmentIdQuestionsResponses[keyof GetCandidateAssessmentsCandidateAssessmentIdQuestionsResponses];

export type GetCandidateAssessmentsCandidateAssessmentIdQuestionsQuestionIdData = {
    body?: never;
    path: {
        /**
         * Unique ID of a CandidateAssessment
         */
        candidateAssessmentId: string;
        /**
         * Unique ID of a Question
         */
        questionId: string;
    };
    query?: never;
    url: '/candidate-assessments/{candidateAssessmentId}/questions/{questionId}';
};

export type GetCandidateAssessmentsCandidateAssessmentIdQuestionsQuestionIdErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * The 404 (Not Found) status code indicates that the origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
     */
    404: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type GetCandidateAssessmentsCandidateAssessmentIdQuestionsQuestionIdError = GetCandidateAssessmentsCandidateAssessmentIdQuestionsQuestionIdErrors[keyof GetCandidateAssessmentsCandidateAssessmentIdQuestionsQuestionIdErrors];

export type GetCandidateAssessmentsCandidateAssessmentIdQuestionsQuestionIdResponses = {
    /**
     * Single Question
     */
    200: {
        data: Question;
        links?: LinksCurrentQuestion;
    };
};

export type GetCandidateAssessmentsCandidateAssessmentIdQuestionsQuestionIdResponse = GetCandidateAssessmentsCandidateAssessmentIdQuestionsQuestionIdResponses[keyof GetCandidateAssessmentsCandidateAssessmentIdQuestionsQuestionIdResponses];

export type GetCandidateAssessmentsCandidateAssessmentIdReportsData = {
    body?: never;
    path: {
        /**
         * Unique ID of a CandidateAssessment
         */
        candidateAssessmentId: string;
    };
    query?: {
        /**
         * page[size] and/or page[number] for pagination.
         */
        page?: Array<unknown>;
    };
    url: '/candidate-assessments/{candidateAssessmentId}/reports';
};

export type GetCandidateAssessmentsCandidateAssessmentIdReportsErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type GetCandidateAssessmentsCandidateAssessmentIdReportsError = GetCandidateAssessmentsCandidateAssessmentIdReportsErrors[keyof GetCandidateAssessmentsCandidateAssessmentIdReportsErrors];

export type GetCandidateAssessmentsCandidateAssessmentIdReportsResponses = {
    /**
     * Collection of Reports.
     */
    200: {
        data: Array<Report>;
        meta: MetaCollectionPagination;
        links?: {
            pagination: LinksCollectionPagination;
        };
    };
};

export type GetCandidateAssessmentsCandidateAssessmentIdReportsResponse = GetCandidateAssessmentsCandidateAssessmentIdReportsResponses[keyof GetCandidateAssessmentsCandidateAssessmentIdReportsResponses];

export type GetCandidateAssessmentsCandidateAssessmentIdReportsCandidateReportIdData = {
    body?: never;
    path: {
        /**
         * Unique ID of a CandidateAssessment
         */
        candidateAssessmentId: string;
        /**
         * Unique ID of a CandidateReport
         */
        candidateReportId: string;
    };
    query?: never;
    url: '/candidate-assessments/{candidateAssessmentId}/reports/{candidateReportId}';
};

export type GetCandidateAssessmentsCandidateAssessmentIdReportsCandidateReportIdErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * The 404 (Not Found) status code indicates that the origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
     */
    404: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type GetCandidateAssessmentsCandidateAssessmentIdReportsCandidateReportIdError = GetCandidateAssessmentsCandidateAssessmentIdReportsCandidateReportIdErrors[keyof GetCandidateAssessmentsCandidateAssessmentIdReportsCandidateReportIdErrors];

export type GetCandidateAssessmentsCandidateAssessmentIdReportsCandidateReportIdResponses = {
    /**
     * Single CandidateReport.
     */
    200: Blob | File;
};

export type GetCandidateAssessmentsCandidateAssessmentIdReportsCandidateReportIdResponse = GetCandidateAssessmentsCandidateAssessmentIdReportsCandidateReportIdResponses[keyof GetCandidateAssessmentsCandidateAssessmentIdReportsCandidateReportIdResponses];

export type GetCandidateAssessmentsCandidateAssessmentIdScoreSetsData = {
    body?: never;
    path: {
        /**
         * Unique ID of a CandidateAssessment
         */
        candidateAssessmentId: string;
    };
    query?: never;
    url: '/candidate-assessments/{candidateAssessmentId}/score-sets';
};

export type GetCandidateAssessmentsCandidateAssessmentIdScoreSetsErrors = {
    /**
     * Bad Request.
     */
    400: {
        errors: Array<Error>;
    };
    /**
     * The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
     */
    401: {
        errors: Array<Error>;
    };
    /**
     * The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it. A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
     * Use for valid credentials that lack access to a resource.
     */
    403: {
        errors: Array<Error>;
    };
    /**
     * The 404 (Not Found) status code indicates that the origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
     */
    404: {
        errors: Array<Error>;
    };
    /**
     * Not Acceptable.
     */
    406: {
        errors: Array<Error>;
    };
    /**
     * Unsupported Media Type.
     */
    415: {
        errors: Array<Error>;
    };
    /**
     * Too Many Requests.
     */
    429: {
        errors: Array<Error>;
    };
    /**
     * Internal Server Error.
     */
    500: {
        errors: Array<Error>;
    };
};

export type GetCandidateAssessmentsCandidateAssessmentIdScoreSetsError = GetCandidateAssessmentsCandidateAssessmentIdScoreSetsErrors[keyof GetCandidateAssessmentsCandidateAssessmentIdScoreSetsErrors];

export type GetCandidateAssessmentsCandidateAssessmentIdScoreSetsResponses = {
    /**
     * Single ScoreSet.
     */
    200: {
        data: ScoreSet;
    };
};

export type GetCandidateAssessmentsCandidateAssessmentIdScoreSetsResponse = GetCandidateAssessmentsCandidateAssessmentIdScoreSetsResponses[keyof GetCandidateAssessmentsCandidateAssessmentIdScoreSetsResponses];
